# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc3.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(409, 340)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(0, 0, 401, 71))
        self.lcdNumber.setDigitCount(15)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 70, 401, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.n4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.n4.setObjectName("n4")
        self.gridLayout.addWidget(self.n4, 1, 0, 1, 1)
        self.n1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.n1.setObjectName("n1")
        self.gridLayout.addWidget(self.n1, 2, 0, 1, 1)
        self.multi = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.multi.setObjectName("multi")
        self.gridLayout.addWidget(self.multi, 1, 3, 1, 1)
        self.n6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.n6.setObjectName("n6")
        self.gridLayout.addWidget(self.n6, 1, 2, 1, 1)
        self.equal = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.equal.setObjectName("equal")
        self.gridLayout.addWidget(self.equal, 2, 3, 1, 1)
        self.n3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.n3.setObjectName("n3")
        self.gridLayout.addWidget(self.n3, 2, 2, 1, 1)
        self.division = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.division.setObjectName("division")
        self.gridLayout.addWidget(self.division, 0, 3, 1, 1)
        self.n7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.n7.setObjectName("n7")
        self.gridLayout.addWidget(self.n7, 0, 0, 1, 1)
        self.n2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.n2.setObjectName("n2")
        self.gridLayout.addWidget(self.n2, 2, 1, 1, 1)
        self.minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.minus.setObjectName("minus")
        self.gridLayout.addWidget(self.minus, 1, 4, 1, 1)
        self.n5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.n5.setObjectName("n5")
        self.gridLayout.addWidget(self.n5, 1, 1, 1, 1)
        self.n9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.n9.setObjectName("n9")
        self.gridLayout.addWidget(self.n9, 0, 2, 1, 1)
        self.clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.clear.setObjectName("clear")
        self.gridLayout.addWidget(self.clear, 2, 4, 1, 1)
        self.n8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.n8.setObjectName("n8")
        self.gridLayout.addWidget(self.n8, 0, 1, 1, 1)
        self.plus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.plus.setObjectName("plus")
        self.gridLayout.addWidget(self.plus, 0, 4, 1, 1)
        self.n0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.n0.setObjectName("n0")
        self.gridLayout.addWidget(self.n0, 3, 1, 1, 1)
        self.dot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.dot.setObjectName("dot")
        self.gridLayout.addWidget(self.dot, 3, 2, 1, 1)
        self.cancelEntry = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cancelEntry.setObjectName("cancelEntry")
        self.gridLayout.addWidget(self.cancelEntry, 3, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.n4.setText(_translate("MainWindow", "4"))
        self.n1.setText(_translate("MainWindow", "1"))
        self.multi.setText(_translate("MainWindow", "*"))
        self.n6.setText(_translate("MainWindow", "6"))
        self.equal.setText(_translate("MainWindow", "="))
        self.n3.setText(_translate("MainWindow", "3"))
        self.division.setText(_translate("MainWindow", "/"))
        self.n7.setText(_translate("MainWindow", "7"))
        self.n2.setText(_translate("MainWindow", "2"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.n5.setText(_translate("MainWindow", "5"))
        self.n9.setText(_translate("MainWindow", "9"))
        self.clear.setText(_translate("MainWindow", "C"))
        self.n8.setText(_translate("MainWindow", "8"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.n0.setText(_translate("MainWindow", "0"))
        self.dot.setText(_translate("MainWindow", "."))
        self.cancelEntry.setText(_translate("MainWindow", "CE"))

